### ISSUE TITLE
./bin/generate throws SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by thomasmodeneis** [mz026/universal-redux-template#19]
Hi,

When I try to run `./bin/generate component myNamespace/MyComponent`

```js
(function (exports, require, module, __filename, __dirname) { import { execSync } from 'child_process';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at loader (/opt/test-react/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/opt/test-react/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
```

What do I need in order to have this working ??
I've upgraded NodeJS to: 
`$ node --version -> v6.0.0`

Thanks

**Comment by thomasmodeneis** [comment]
I've got same error as well for npm test
```
$ npm test

> universal-redux-template@0.0.0 test /opt/test-react
> cross-env NODE_ENV=test cross-env NODE_PATH=./app mocha --compilers js:babel-register -r app/spec/support/setup.mocha.js --recursive 'app/spec/**/*.test.js' -w

/opt/test-react/app/spec/support/setup.mocha.js:1
(function (exports, require, module, __filename, __dirname) { import chai from 'chai';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at loader (/opt/test-react/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/opt/test-react/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at /opt/test-react/node_modules/mocha/bin/_mocha:310:3
    at Array.forEach (native)
    at Object.<anonymous> (/opt/test-react/node_modules/mocha/bin/_mocha:309:10)
    at Module._compile (module.js:541:32)
npm ERR! Test failed.  See above for more details.
```

And I downgraded node to 5.6.0 as it says on your package.json and tried my luck, but I got same error, any ideas ?

**Comment by mz026** [comment]
I can't reproduce it on my machine. Did you modify any settings before running the commands?

**Comment by mz026** [comment]
Could you try to remove the `node_module`, switch back to node 5.6.0 and install all the dependencies to see if it works?

**Comment by mz026** [comment]
@thomasmodeneis  I was able to reproduce the issue you mentioned by remove `es2015` in the `presets` section of `.babelrc`, but I'm not sure if it was your case. Could you provide your `.babelrc`?

**Comment by thomasmodeneis** [comment]
Hi @mz026 

I did not change any of the cfgs, I just had an old NodeJS (0.10.x) and upgraded to 6.0.0 and got into this problem.

So, I've removed all the modules, downgraded node to 5.6.0 and it took few hours I'm not sure why yet, but now I'm getting different error when trying to generate:
```
$ ./bin/generate component myNamespace/MyComponent
mkdir...
copy files...
sed...
sed: 1: "/opt/test-react/ ...": command c expects \ followed by text
child_process.js:507
    throw err;
    ^

Error: Command failed: sed -i 's/COMPONENT_NAME/MyComponent/g' /opt/test-react/app/components/myNamespace/MyComponent.js
sed: 1: "/opt/test-react/ ...": command c expects \ followed by text

    at checkExecSyncError (child_process.js:464:13)
    at execSync (child_process.js:504:13)
    at sed (_generate.js:72:3)
    at Object.<anonymous> (_generate.js:10:1)
    at Module._compile (module.js:413:34)
    at loader (/opt/test-react/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/opt/test-react/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

This is the babel cfg:
```js
{
  "presets": ["es2015", "react"],
  "env": {
    "test": {
      "plugins": [ "babel-plugin-rewire" ]
    }
  }
}
```

**Comment by mz026** [comment]
@thomasmodeneis It's related to [`sed` command on osx](http://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux), I'll fix it later.

As a work around, you can update the `sed` part in `bin/_generate.js` from:

```
`sed -i 's/...`
```
to
```
`sed -i '' 's/...`
```
(with the aditional `''`) to make it work.

Btw, does the `npm start` issue https://github.com/mz026/universal-redux-template/issues/20 still occur after the re-installing of the modules?

**Comment by thomasmodeneis** [comment]
Yey, that works sweeeet :D
Thank you @mz026

**Comment by thomasmodeneis** [comment]
yes #20 now works after downgrade and re-installing of the modules

**Comment by mz026** [comment]
@thomasmodeneis this commit https://github.com/mz026/universal-redux-template/commit/81e2c31c32585ed5dd4805d8d989e2689562637c should fix `sed` issue on mac osx
