### ISSUE TITLE
use  css-loader in webpackage,but not work?

### ISSUE THREAD

**Issue by JK666** [mz026/universal-redux-template#50]
我想在 react components 內 載入 css 製作 ui, 於是我使用了 css-loader 於 webpackage,
但我依據webpackage2.2 官方建議的的使用方法都無法順利加載 css,不知道是什麼問題？

SyntaxError: /Users/Allen/Documents/react/universal-redux-template-master/app/components/Nav/NavC1.css: Unexpected token (1:0)
[0] > 1 | .header {
[0]     | ^
[0]   2 |   color: #00ccff;
[0]   3 | }
[0]     at Parser.pp$5.raise (/Users/Allen/Documents/react/universal-redux-template-master/node_modules/babylon/lib/index.js:4246:13)
[0]     at Parser.pp.unexpected (/Users/Allen/Documents/react/universal-redux-template-master/node_modules/babylon/lib/index.js:1627:8)
[0]     at Parser.pp$3.parseExprAtom (/Users/Allen/Documents/react/universal-redux-template-master/node_modules/babylon/lib/index.js:3586:12)
[0]     at Parser.parseExprAtom (/Users/Allen/Documents/react/universal-redux-template-master/node_modules/babylon/lib/index.js:6402:22)
[0]     at Parser.pp$3.parseExprSubscripts (/Users/Allen/Documents/react/universal-redux-template-master/node_modules/babylon/lib/index.js:3331:19)
[0]     at Parser.pp$3.parseMaybeUnary (/Users/Allen/Documents/react/universal-redux-template-master/node_modules/babylon/lib/index.js:3311:19)
[0]     at Parser.pp$3.parseExprOps (/Users/Allen/Documents/react/universal-redux-template-master/node_modules/babylon/lib/index.js:3241:19)
[0]     at Parser.pp$3.parseMaybeConditional (/Users/Allen/Documents/react/universal-redux-template-master/node_modules/babylon/lib/index.js:3218:19)
[0]     at Parser.pp$3.parseMaybeAssign (/Users/Allen/Documents/react/universal-redux-template-master/node_modules/babylon/lib/index.js:3181:19)
[0]     at Parser.parseMaybeAssign (/Users/Allen/Documents/react/universal-redux-template-master/node_modules/babylon/lib/index.js:5694:20)
[0]     at Parser.pp$3.parseExpression (/Users/Allen/Documents/react/universal-redux-template-master/node_modules/babylon/lib/index.js:3143:19)
[0]     at Parser.pp$1.parseStatement (/Users/Allen/Documents/react/universal-redux-template-master/node_modules/babylon/lib/index.js:1774:19)
[0]     at Parser.parseStatement (/Users/Allen/Documents/react/universal-redux-template-master/node_modules/babylon/lib/index.js:5218:22)
[0]     at Parser.pp$1.parseBlockBody (/Users/Allen/Documents/react/universal-redux-template-master/node_modules/babylon/lib/index.js:2133:21)
[0]     at Parser.pp$1.parseTopLevel (/Users/Allen/Documents/react/universal-redux-template-master/node_modules/babylon/lib/index.js:1645:8)
[0]     at Parser.parse (/Users/Allen/Documents/react/universal-redux-template-master/node_modules/babylon/lib/index.js:1537:17)
[0] [nodemon] app crashed - waiting for file changes before starting...

**Comment by mz026** [comment]
@JK666 這個 starter kit 目前處理 css 的作法是用 `gulp` + `node-sass` 耶，所以在沒有修改 `webpack.config.js` 的狀況下，直接在 javascript file 裡面 `import` css 是無法運作的。

如果要在javascript 裡面 import css 檔案的話，應該是要修改 `webpack.config.js` 的設定，在其中加入相對應的 loader。
